//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDriveResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoDriveResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounting.
        /// </summary>
        public static string accounting {
            get {
                return ResourceManager.GetString("accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add CertificationSpecific.
        /// </summary>
        public static string Add_CertificationSpecifics {
            get {
                return ResourceManager.GetString("Add CertificationSpecifics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string Add_Item {
            get {
                return ResourceManager.GetString("Add_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ArchiveSettingHR.
        /// </summary>
        public static string AddArchiveSettingHR {
            get {
                return ResourceManager.GetString("AddArchiveSettingHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Area.
        /// </summary>
        public static string AddArea {
            get {
                return ResourceManager.GetString("AddArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add BloodGroup.
        /// </summary>
        public static string AddBloodGroup {
            get {
                return ResourceManager.GetString("AddBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add CarrerField.
        /// </summary>
        public static string AddCarrerField {
            get {
                return ResourceManager.GetString("AddCarrerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add CertificationSpecDeparts.
        /// </summary>
        public static string AddCertificationSpecDeparts {
            get {
                return ResourceManager.GetString("AddCertificationSpecDeparts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add CertificationType.
        /// </summary>
        public static string AddCertificationType {
            get {
                return ResourceManager.GetString("AddCertificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Country.
        /// </summary>
        public static string AddCountry {
            get {
                return ResourceManager.GetString("AddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Department.
        /// </summary>
        public static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DriveLevel.
        /// </summary>
        public static string AddDriveLevel {
            get {
                return ResourceManager.GetString("AddDriveLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddEmployee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JobName.
        /// </summary>
        public static string AddJobName {
            get {
                return ResourceManager.GetString("AddJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddLicenceCategory.
        /// </summary>
        public static string AddLicenceCategory {
            get {
                return ResourceManager.GetString("AddLicenceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add LicenceType.
        /// </summary>
        public static string AddLicenceType {
            get {
                return ResourceManager.GetString("AddLicenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add LicenceType.
        /// </summary>
        public static string AddLicenceTypeHR {
            get {
                return ResourceManager.GetString("AddLicenceTypeHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MaritalStatuse.
        /// </summary>
        public static string AddMaritalStatu {
            get {
                return ResourceManager.GetString("AddMaritalStatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Motivation Type.
        /// </summary>
        public static string AddMotivationType {
            get {
                return ResourceManager.GetString("AddMotivationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Nationality.
        /// </summary>
        public static string AddNationality {
            get {
                return ResourceManager.GetString("AddNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add National Type.
        /// </summary>
        public static string AddNationalType {
            get {
                return ResourceManager.GetString("AddNationalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Base Department.
        /// </summary>
        public static string AddNewBaseDepartment {
            get {
                return ResourceManager.GetString("AddNewBaseDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddReceipt Voucher.
        /// </summary>
        public static string AddReceiptVoucher {
            get {
                return ResourceManager.GetString("AddReceiptVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Religion.
        /// </summary>
        public static string AddReligion {
            get {
                return ResourceManager.GetString("AddReligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Speech Language.
        /// </summary>
        public static string AddSpeechLanguage {
            get {
                return ResourceManager.GetString("AddSpeechLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddStudy PeriodSetting.
        /// </summary>
        public static string AddStudyPeriodSetting {
            get {
                return ResourceManager.GetString("AddStudyPeriodSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Test.
        /// </summary>
        public static string AddTest {
            get {
                return ResourceManager.GetString("AddTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TestResult.
        /// </summary>
        public static string AddTestResult {
            get {
                return ResourceManager.GetString("AddTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trainee Attendance.
        /// </summary>
        public static string AddTraineeAttendance {
            get {
                return ResourceManager.GetString("AddTraineeAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTraineeAttendingFollowup.
        /// </summary>
        public static string AddTraineeAttendingFollowup {
            get {
                return ResourceManager.GetString("AddTraineeAttendingFollowup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddWorkTimes Setting.
        /// </summary>
        public static string AddWorkTimesSetting {
            get {
                return ResourceManager.GetString("AddWorkTimesSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot be done to approve the salary. Please enter another period.
        /// </summary>
        public static string ApprovalSalary {
            get {
                return ResourceManager.GetString("ApprovalSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Document.
        /// </summary>
        public static string ArchiveDocument {
            get {
                return ResourceManager.GetString("ArchiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Setting Drive.
        /// </summary>
        public static string ArchiveSettingDrive {
            get {
                return ResourceManager.GetString("ArchiveSettingDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Main Item--.
        /// </summary>
        public static string ArchiveSettingHRDropDown {
            get {
                return ResourceManager.GetString("ArchiveSettingHRDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Files items.
        /// </summary>
        public static string ArchiveSettingHRs {
            get {
                return ResourceManager.GetString("ArchiveSettingHRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Area Source--.
        /// </summary>
        public static string areasDropDown {
            get {
                return ResourceManager.GetString("areasDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArName.
        /// </summary>
        public static string ArName {
            get {
                return ResourceManager.GetString("ArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Date.
        /// </summary>
        public static string AttendanceDate {
            get {
                return ResourceManager.GetString("AttendanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoDriveMain.
        /// </summary>
        public static string AutoDriveMain {
            get {
                return ResourceManager.GetString("AutoDriveMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackBtn {
            get {
                return ResourceManager.GetString("BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Codes.
        /// </summary>
        public static string BasicCode {
            get {
                return ResourceManager.GetString("BasicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Groups.
        /// </summary>
        public static string BloodGroup {
            get {
                return ResourceManager.GetString("BloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Bloodgroup--.
        /// </summary>
        public static string BloodGroupsDropDown {
            get {
                return ResourceManager.GetString("BloodGroupsDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff salaries have been successfully calculated.
        /// </summary>
        public static string CalculateSalaries {
            get {
                return ResourceManager.GetString("CalculateSalaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot be done to cancel the salary. Please enter another period.
        /// </summary>
        public static string CanceledSalary {
            get {
                return ResourceManager.GetString("CanceledSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrer Field.
        /// </summary>
        public static string CarrerField {
            get {
                return ResourceManager.GetString("CarrerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Carrer Filed--.
        /// </summary>
        public static string CarrerFieldDropDown {
            get {
                return ResourceManager.GetString("CarrerFieldDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --select certification Grade--.
        /// </summary>
        public static string certificationGradeDropDown {
            get {
                return ResourceManager.GetString("certificationGradeDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select certification Department--.
        /// </summary>
        public static string certificationSpecDepartDropDown {
            get {
                return ResourceManager.GetString("certificationSpecDepartDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CertificationSpecDeparts.
        /// </summary>
        public static string CertificationSpecDeparts {
            get {
                return ResourceManager.GetString("CertificationSpecDeparts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select certification Specifics--.
        /// </summary>
        public static string certificationSpecificDropDown {
            get {
                return ResourceManager.GetString("certificationSpecificDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CertificationSpecifics.
        /// </summary>
        public static string CertificationSpecifics {
            get {
                return ResourceManager.GetString("CertificationSpecifics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Types.
        /// </summary>
        public static string CertificationType {
            get {
                return ResourceManager.GetString("CertificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select CertificationType--.
        /// </summary>
        public static string certificationTypeDropDown {
            get {
                return ResourceManager.GetString("certificationTypeDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose A Day.
        /// </summary>
        public static string ChooseADay {
            get {
                return ResourceManager.GetString("ChooseADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Course Day--.
        /// </summary>
        public static string ChooseAttendanceDay {
            get {
                return ResourceManager.GetString("ChooseAttendanceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose Code--.
        /// </summary>
        public static string ChooseCode {
            get {
                return ResourceManager.GetString("ChooseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose Employee--.
        /// </summary>
        public static string ChooseEmployee {
            get {
                return ResourceManager.GetString("ChooseEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose Employee--.
        /// </summary>
        public static string ChooseEmployeeSafe {
            get {
                return ResourceManager.GetString("ChooseEmployeeSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose Level--.
        /// </summary>
        public static string ChooseLevel {
            get {
                return ResourceManager.GetString("ChooseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose LicenceCategory--.
        /// </summary>
        public static string ChooseLicenceCategory {
            get {
                return ResourceManager.GetString("ChooseLicenceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose LiceneType--.
        /// </summary>
        public static string ChooseLiceneType {
            get {
                return ResourceManager.GetString("ChooseLiceneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Test.
        /// </summary>
        public static string ChooseTestId {
            get {
                return ResourceManager.GetString("ChooseTestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose TestResult.
        /// </summary>
        public static string ChooseTestResultId {
            get {
                return ResourceManager.GetString("ChooseTestResultId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --ChooseTrainee--.
        /// </summary>
        public static string ChooseTrainee {
            get {
                return ResourceManager.GetString("ChooseTrainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose Trainee Code--.
        /// </summary>
        public static string ChooseTraineeCode {
            get {
                return ResourceManager.GetString("ChooseTraineeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Type--.
        /// </summary>
        public static string ChoseType {
            get {
                return ResourceManager.GetString("ChoseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmBtn {
            get {
                return ResourceManager.GetString("ConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Confirm the deletion process !.
        /// </summary>
        public static string ConfirmDeleteMsg {
            get {
                return ResourceManager.GetString("ConfirmDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Country--.
        /// </summary>
        public static string CountryDropDown {
            get {
                return ResourceManager.GetString("CountryDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countrys.
        /// </summary>
        public static string Countrys {
            get {
                return ResourceManager.GetString("Countrys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Reservation.
        /// </summary>
        public static string CourseReservation {
            get {
                return ResourceManager.GetString("CourseReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this Data Already Saved Befor For This Employe.
        /// </summary>
        public static string DataSavedBefor {
            get {
                return ResourceManager.GetString("DataSavedBefor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day_ofWeek {
            get {
                return ResourceManager.GetString("Day_ofWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DaysWork {
            get {
                return ResourceManager.GetString("DaysWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases and Deductions Deleted..
        /// </summary>
        public static string DeductionDeleted {
            get {
                return ResourceManager.GetString("DeductionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases and Deductions Edited..
        /// </summary>
        public static string DeductionEdited {
            get {
                return ResourceManager.GetString("DeductionEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases and Deductions Saved.
        /// </summary>
        public static string DeductionSaved {
            get {
                return ResourceManager.GetString("DeductionSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sort is already exists. Please enter another sort.
        /// </summary>
        public static string DegreeSortValdiation {
            get {
                return ResourceManager.GetString("DegreeSortValdiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Delete Right Now .
        /// </summary>
        public static string DeleteErr {
            get {
                return ResourceManager.GetString("DeleteErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is data for this category. Please delete it first.
        /// </summary>
        public static string Deleterelated {
            get {
                return ResourceManager.GetString("Deleterelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful deletion.
        /// </summary>
        public static string DeleteSucc {
            get {
                return ResourceManager.GetString("DeleteSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Managment--.
        /// </summary>
        public static string DepartmentDropDown {
            get {
                return ResourceManager.GetString("DepartmentDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Search For Department--.
        /// </summary>
        public static string DepartmentSearch {
            get {
                return ResourceManager.GetString("DepartmentSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveLevel.
        /// </summary>
        public static string DriveLevel {
            get {
                return ResourceManager.GetString("DriveLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item.
        /// </summary>
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email adress.
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Attendance and Departure has been deleted.
        /// </summary>
        public static string EmployeeAttendanceDepartureDeleted {
            get {
                return ResourceManager.GetString("EmployeeAttendanceDepartureDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Attendance and Departure has been edited.
        /// </summary>
        public static string EmployeeAttendanceDepartureEdited {
            get {
                return ResourceManager.GetString("EmployeeAttendanceDepartureEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Edit Employee Info .
        /// </summary>
        public static string EmployeeEditInfo {
            get {
                return ResourceManager.GetString("EmployeeEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Main Information.
        /// </summary>
        public static string EmployeeForm1 {
            get {
                return ResourceManager.GetString("EmployeeForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Department.
        /// </summary>
        public static string EmployeeForm2 {
            get {
                return ResourceManager.GetString("EmployeeForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Licence Data.
        /// </summary>
        public static string EmployeeForm3 {
            get {
                return ResourceManager.GetString("EmployeeForm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Qualifications.
        /// </summary>
        public static string EmployeeForm4 {
            get {
                return ResourceManager.GetString("EmployeeForm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Contract Duration.
        /// </summary>
        public static string EmployeeForm5 {
            get {
                return ResourceManager.GetString("EmployeeForm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Experiences.
        /// </summary>
        public static string EmployeeForm6 {
            get {
                return ResourceManager.GetString("EmployeeForm6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Data.
        /// </summary>
        public static string EmployeeForm7 {
            get {
                return ResourceManager.GetString("EmployeeForm7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Employee..
        /// </summary>
        public static string EmployeeRequired {
            get {
                return ResourceManager.GetString("EmployeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for employee.
        /// </summary>
        public static string EmployeeSearch {
            get {
                return ResourceManager.GetString("EmployeeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Contact Status--.
        /// </summary>
        public static string EmployeeStatusDropDown {
            get {
                return ResourceManager.GetString("EmployeeStatusDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation has been added.
        /// </summary>
        public static string EmployeeVacationAdded {
            get {
                return ResourceManager.GetString("EmployeeVacationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Vacation Balance has been deleted..
        /// </summary>
        public static string EmployeeVacationBalanceDeleted {
            get {
                return ResourceManager.GetString("EmployeeVacationBalanceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Vacation Balance has been edited.
        /// </summary>
        public static string EmployeeVacationBalanceEdited {
            get {
                return ResourceManager.GetString("EmployeeVacationBalanceEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation has been deleted.
        /// </summary>
        public static string EmployeeVacationDeleted {
            get {
                return ResourceManager.GetString("EmployeeVacationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation has been edited.
        /// </summary>
        public static string EmployeeVacationEdited {
            get {
                return ResourceManager.GetString("EmployeeVacationEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Working Hours have been deleted.
        /// </summary>
        public static string EmployeeWorkingHoursDeleted {
            get {
                return ResourceManager.GetString("EmployeeWorkingHoursDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Working Hours have been edited.
        /// </summary>
        public static string EmployeeWorkingHoursEdited {
            get {
                return ResourceManager.GetString("EmployeeWorkingHoursEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate must be greater than StartDate.
        /// </summary>
        public static string EndDateError {
            get {
                return ResourceManager.GetString("EndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnName.
        /// </summary>
        public static string EnName {
            get {
                return ResourceManager.GetString("EnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the addition, please try again.
        /// </summary>
        public static string ErrorAdding {
            get {
                return ResourceManager.GetString("ErrorAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, try again.
        /// </summary>
        public static string ErrorDataBase {
            get {
                return ResourceManager.GetString("ErrorDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during deletion. Please try again.
        /// </summary>
        public static string ErrorDeletion {
            get {
                return ResourceManager.GetString("ErrorDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the modification, please try again.
        /// </summary>
        public static string ErrorModification {
            get {
                return ResourceManager.GetString("ErrorModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This balance is already Existed.Please enter anthor balance.
        /// </summary>
        public static string ExistedBalance {
            get {
                return ResourceManager.GetString("ExistedBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data is duplicate, please enter other data.
        /// </summary>
        public static string ExistedEmployeeAttendance {
            get {
                return ResourceManager.GetString("ExistedEmployeeAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Working Hours is existed for the same employee in that period, please choose another period.
        /// </summary>
        public static string ExistedEmployeeWorkingHours {
            get {
                return ResourceManager.GetString("ExistedEmployeeWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists. Please enter another name.
        /// </summary>
        public static string ExistedName {
            get {
                return ResourceManager.GetString("ExistedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This employee has a vacation in that period. Please choose another period.
        /// </summary>
        public static string ExistedVacation {
            get {
                return ResourceManager.GetString("ExistedVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This working hours is existed.Please enter another continuity..
        /// </summary>
        public static string ExistedWorkingHoursSettingHR {
            get {
                return ResourceManager.GetString("ExistedWorkingHoursSettingHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This working hours is existed in that period, please choose another period.
        /// </summary>
        public static string ExistedWorkingHoursSettingInPeriod {
            get {
                return ResourceManager.GetString("ExistedWorkingHoursSettingInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friday.
        /// </summary>
        public static string fri {
            get {
                return ResourceManager.GetString("fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Gender--.
        /// </summary>
        public static string GenderDropDown {
            get {
                return ResourceManager.GetString("GenderDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HonestyDate.
        /// </summary>
        public static string HonestyDate {
            get {
                return ResourceManager.GetString("HonestyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to honesty End Date.
        /// </summary>
        public static string honestyEndDate {
            get {
                return ResourceManager.GetString("honestyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resource.
        /// </summary>
        public static string HumanResource {
            get {
                return ResourceManager.GetString("HumanResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size is more than 3MB.
        /// </summary>
        public static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases and Deductions Type Deleted..
        /// </summary>
        public static string IncreasesDeductionTypeDeleted {
            get {
                return ResourceManager.GetString("IncreasesDeductionTypeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases and Deductions Type Edited..
        /// </summary>
        public static string IncreasesDeductionTypeEdited {
            get {
                return ResourceManager.GetString("IncreasesDeductionTypeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases and Deductions Type Saved..
        /// </summary>
        public static string IncreasesDeductionTypeSaved {
            get {
                return ResourceManager.GetString("IncreasesDeductionTypeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing and Deduction Type Edited.
        /// </summary>
        public static string IncreasingDeductionTypeEdited {
            get {
                return ResourceManager.GetString("IncreasingDeductionTypeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing and Deduction Type Saved.
        /// </summary>
        public static string IncreasingDeductionTypeSaved {
            get {
                return ResourceManager.GetString("IncreasingDeductionTypeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter In Month..
        /// </summary>
        public static string InMonthRequired {
            get {
                return ResourceManager.GetString("InMonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Img Size.
        /// </summary>
        public static string InvalidImgSize {
            get {
                return ResourceManager.GetString("InvalidImgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter In Year..
        /// </summary>
        public static string InYearRequired {
            get {
                return ResourceManager.GetString("InYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemCode.
        /// </summary>
        public static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Choose Item--.
        /// </summary>
        public static string ItemDropDown {
            get {
                return ResourceManager.GetString("ItemDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصنف.
        /// </summary>
        public static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item To.
        /// </summary>
        public static string Itemto {
            get {
                return ResourceManager.GetString("Itemto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job degree has been deleted.
        /// </summary>
        public static string JobDegreeDelete {
            get {
                return ResourceManager.GetString("JobDegreeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select JobDegree --.
        /// </summary>
        public static string JobDegreeDropDown {
            get {
                return ResourceManager.GetString("JobDegreeDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Degree Edited.
        /// </summary>
        public static string JobDegreeEdit {
            get {
                return ResourceManager.GetString("JobDegreeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Degree saved.
        /// </summary>
        public static string JobDegreeSave {
            get {
                return ResourceManager.GetString("JobDegreeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Function.
        /// </summary>
        public static string JobFunction {
            get {
                return ResourceManager.GetString("JobFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select JobFunction--.
        /// </summary>
        public static string JobFunctionDropDown {
            get {
                return ResourceManager.GetString("JobFunctionDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Degree Deleted.
        /// </summary>
        public static string JobLevelDelete {
            get {
                return ResourceManager.GetString("JobLevelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Job Level--.
        /// </summary>
        public static string JobLevelDropDown {
            get {
                return ResourceManager.GetString("JobLevelDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Level Edited.
        /// </summary>
        public static string JobLevelEdit {
            get {
                return ResourceManager.GetString("JobLevelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Level Saved.
        /// </summary>
        public static string JobLevelSave {
            get {
                return ResourceManager.GetString("JobLevelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobName.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select JobName--.
        /// </summary>
        public static string JobNameDropDown {
            get {
                return ResourceManager.GetString("JobNameDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job level already exists to this degree. Please enter another job level.
        /// </summary>
        public static string LevelToJobDergee {
            get {
                return ResourceManager.GetString("LevelToJobDergee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicenceCategory.
        /// </summary>
        public static string LicenceCategory {
            get {
                return ResourceManager.GetString("LicenceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select licenceKind--.
        /// </summary>
        public static string licenceKindHRsDropDown {
            get {
                return ResourceManager.GetString("licenceKindHRsDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicenceType.
        /// </summary>
        public static string LicenceType {
            get {
                return ResourceManager.GetString("LicenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicenceType.
        /// </summary>
        public static string LicenceTypeHR {
            get {
                return ResourceManager.GetString("LicenceTypeHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select licenceType--.
        /// </summary>
        public static string licenceTypeHRDropDown {
            get {
                return ResourceManager.GetString("licenceTypeHRDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan has been added.
        /// </summary>
        public static string LoanAdded {
            get {
                return ResourceManager.GetString("LoanAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan has been deleted.
        /// </summary>
        public static string LoanDeleted {
            get {
                return ResourceManager.GetString("LoanDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan has been edited.
        /// </summary>
        public static string LoanEdited {
            get {
                return ResourceManager.GetString("LoanEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Files Items.
        /// </summary>
        public static string MainArchiveSettingHRs {
            get {
                return ResourceManager.GetString("MainArchiveSettingHRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Departments.
        /// </summary>
        public static string MainDepartments {
            get {
                return ResourceManager.GetString("MainDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Item.
        /// </summary>
        public static string MainItem {
            get {
                return ResourceManager.GetString("MainItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Items.
        /// </summary>
        public static string MainSelected_Item {
            get {
                return ResourceManager.GetString("MainSelected_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Statuse.
        /// </summary>
        public static string MaritalStatu {
            get {
                return ResourceManager.GetString("MaritalStatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --select MaritalStatu--.
        /// </summary>
        public static string MaritalStatuDropDown {
            get {
                return ResourceManager.GetString("MaritalStatuDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modday.
        /// </summary>
        public static string mon {
            get {
                return ResourceManager.GetString("mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Month--.
        /// </summary>
        public static string MonthsDropDown {
            get {
                return ResourceManager.GetString("MonthsDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Motivation Date..
        /// </summary>
        public static string MotivationDateRequired {
            get {
                return ResourceManager.GetString("MotivationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Status..
        /// </summary>
        public static string MotivationStatusRequired {
            get {
                return ResourceManager.GetString("MotivationStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivation Type.
        /// </summary>
        public static string MotivationType {
            get {
                return ResourceManager.GetString("MotivationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Motivation Type..
        /// </summary>
        public static string MotivationTypeRequired {
            get {
                return ResourceManager.GetString("MotivationTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Already Exist.
        /// </summary>
        public static string NameAlreadyExist {
            get {
                return ResourceManager.GetString("NameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already exists. Please enter another name.
        /// </summary>
        public static string NameValidationError {
            get {
                return ResourceManager.GetString("NameValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Nationality--.
        /// </summary>
        public static string NationalityDropDown {
            get {
                return ResourceManager.GetString("NationalityDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Type.
        /// </summary>
        public static string NationalType {
            get {
                return ResourceManager.GetString("NationalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result Founded.
        /// </summary>
        public static string NoResultFounded {
            get {
                return ResourceManager.GetString("NoResultFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotActive.
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employee has been chosen to approve the salary.
        /// </summary>
        public static string NotCheckedEmployee {
            get {
                return ResourceManager.GetString("NotCheckedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Working Hours are chosen, please choose.
        /// </summary>
        public static string NotCheckWorkingHours {
            get {
                return ResourceManager.GetString("NotCheckWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough balance for this vacation. Please choose another period.
        /// </summary>
        public static string NotEnoughBalance {
            get {
                return ResourceManager.GetString("NotEnoughBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no balance for this vacation..
        /// </summary>
        public static string NotExistedBalance {
            get {
                return ResourceManager.GetString("NotExistedBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Changed Salary.
        /// </summary>
        public static string NotExistedChangedSalary {
            get {
                return ResourceManager.GetString("NotExistedChangedSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data in the table for salary approval..
        /// </summary>
        public static string NotExistedDataforApproval {
            get {
                return ResourceManager.GetString("NotExistedDataforApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Job Degree.
        /// </summary>
        public static string NotExistedDegree {
            get {
                return ResourceManager.GetString("NotExistedDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Employees in the table for salary approval..
        /// </summary>
        public static string NotExistedEmployeesForApproval {
            get {
                return ResourceManager.GetString("NotExistedEmployeesForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Name(EN).
        /// </summary>
        public static string NotExistedENName {
            get {
                return ResourceManager.GetString("NotExistedENName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Increasing and Deduction Type.
        /// </summary>
        public static string NotExistedIncreasingDeductionType {
            get {
                return ResourceManager.GetString("NotExistedIncreasingDeductionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Job Level.
        /// </summary>
        public static string NotExistedLevel {
            get {
                return ResourceManager.GetString("NotExistedLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Name(AR).
        /// </summary>
        public static string NotExistedName {
            get {
                return ResourceManager.GetString("NotExistedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Name.
        /// </summary>
        public static string NotExistedName1 {
            get {
                return ResourceManager.GetString("NotExistedName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Salary.
        /// </summary>
        public static string NotExistedSalary {
            get {
                return ResourceManager.GetString("NotExistedSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotExistedSort.
        /// </summary>
        public static string NotExistedSort {
            get {
                return ResourceManager.GetString("NotExistedSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful operation.
        /// </summary>
        public static string NotSuccessfulOperation {
            get {
                return ResourceManager.GetString("NotSuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill all Filds.
        /// </summary>
        public static string NotValidMsg {
            get {
                return ResourceManager.GetString("NotValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Only.
        /// </summary>
        public static string Numeric_only {
            get {
                return ResourceManager.GetString("Numeric_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has been converted to Payment..
        /// </summary>
        public static string PaymentConverted {
            get {
                return ResourceManager.GetString("PaymentConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practical.
        /// </summary>
        public static string Practical {
            get {
                return ResourceManager.GetString("Practical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practical.
        /// </summary>
        public static string Practicaldays {
            get {
                return ResourceManager.GetString("Practicaldays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practical/Visual.
        /// </summary>
        public static string PracticalOrVisual {
            get {
                return ResourceManager.GetString("PracticalOrVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Voucher.
        /// </summary>
        public static string ReceiptVoucher {
            get {
                return ResourceManager.GetString("ReceiptVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot be done to receive the salary. Please enter another period.
        /// </summary>
        public static string ReceivedSalary {
            get {
                return ResourceManager.GetString("ReceivedSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Honesty Date.
        /// </summary>
        public static string ReceivingHonestyDate {
            get {
                return ResourceManager.GetString("ReceivingHonestyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Honesty From Employee.
        /// </summary>
        public static string ReceivingHonestyFromEmployee {
            get {
                return ResourceManager.GetString("ReceivingHonestyFromEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string Relation {
            get {
                return ResourceManager.GetString("Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Religion--.
        /// </summary>
        public static string ReligionDropDown {
            get {
                return ResourceManager.GetString("ReligionDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Basic Salary/All.
        /// </summary>
        public static string RequiredBasicSalary {
            get {
                return ResourceManager.GetString("RequiredBasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Deduction.
        /// </summary>
        public static string RequiredDeduction {
            get {
                return ResourceManager.GetString("RequiredDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter name.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Ratio/Value.
        /// </summary>
        public static string RequiredRatio {
            get {
                return ResourceManager.GetString("RequiredRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter value.
        /// </summary>
        public static string RequiredValue {
            get {
                return ResourceManager.GetString("RequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary has been adopted.Please choose another month.
        /// </summary>
        public static string RewardAdopted {
            get {
                return ResourceManager.GetString("RewardAdopted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary has been canceled.Please choose another month.
        /// </summary>
        public static string RewardCanceled {
            get {
                return ResourceManager.GetString("RewardCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward has been Edited.
        /// </summary>
        public static string RewardEdited {
            get {
                return ResourceManager.GetString("RewardEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary has been received.Please choose another month.
        /// </summary>
        public static string RewardReceived {
            get {
                return ResourceManager.GetString("RewardReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward has been saved..
        /// </summary>
        public static string rewardSaved {
            get {
                return ResourceManager.GetString("rewardSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The salary has been approved for the chosen employees.
        /// </summary>
        public static string SalaryApprovalForChosenEmployees {
            get {
                return ResourceManager.GetString("SalaryApprovalForChosenEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary deleted..
        /// </summary>
        public static string SalaryDleted {
            get {
                return ResourceManager.GetString("SalaryDleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Edited..
        /// </summary>
        public static string SalaryEdited {
            get {
                return ResourceManager.GetString("SalaryEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Saved..
        /// </summary>
        public static string SalarySaved {
            get {
                return ResourceManager.GetString("SalarySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to enter more than one bonus for the same person in the same month. Please enter a month.
        /// </summary>
        public static string SameMonth {
            get {
                return ResourceManager.GetString("SameMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string sat {
            get {
                return ResourceManager.GetString("sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBTN {
            get {
                return ResourceManager.GetString("SaveBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild Save.
        /// </summary>
        public static string SaveErr {
            get {
                return ResourceManager.GetString("SaveErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Save.
        /// </summary>
        public static string SaveSucc {
            get {
                return ResourceManager.GetString("SaveSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Witout Experience.
        /// </summary>
        public static string SaveWitoutExperience {
            get {
                return ResourceManager.GetString("SaveWitoutExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchBTN {
            get {
                return ResourceManager.GetString("SearchBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Item.
        /// </summary>
        public static string Selected_Item {
            get {
                return ResourceManager.GetString("Selected_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        public static string sEmptyTable {
            get {
                return ResourceManager.GetString("sEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Traffic.
        /// </summary>
        public static string SendToTraffic {
            get {
                return ResourceManager.GetString("SendToTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SettingMenu {
            get {
                return ResourceManager.GetString("SettingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string sFirst {
            get {
                return ResourceManager.GetString("sFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string sInfo {
            get {
                return ResourceManager.GetString("sInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        public static string sInfoEmpty {
            get {
                return ResourceManager.GetString("sInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total entries).
        /// </summary>
        public static string sInfoFiltered {
            get {
                return ResourceManager.GetString("sInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sInfoPostFix {
            get {
                return ResourceManager.GetString("sInfoPostFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sInfoThousands {
            get {
                return ResourceManager.GetString("sInfoThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string sLast {
            get {
                return ResourceManager.GetString("sLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        public static string sLengthMenu {
            get {
                return ResourceManager.GetString("sLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string sLoadingRecords {
            get {
                return ResourceManager.GetString("sLoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string sNext {
            get {
                return ResourceManager.GetString("sNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpeechLanguage.
        /// </summary>
        public static string SpeechLanguage {
            get {
                return ResourceManager.GetString("SpeechLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string sPrevious {
            get {
                return ResourceManager.GetString("sPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string sProcessing {
            get {
                return ResourceManager.GetString("sProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string sSearch {
            get {
                return ResourceManager.GetString("sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate to sort column ascending.
        /// </summary>
        public static string sSortAscending {
            get {
                return ResourceManager.GetString("sSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate to sort column descending.
        /// </summary>
        public static string sSortDescending {
            get {
                return ResourceManager.GetString("sSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudyPeriodSetting.
        /// </summary>
        public static string StudyPeriodSetting {
            get {
                return ResourceManager.GetString("StudyPeriodSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string sun {
            get {
                return ResourceManager.GetString("sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string sZeroRecords {
            get {
                return ResourceManager.GetString("sZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Already Exist.
        /// </summary>
        public static string TestAlreadyExist {
            get {
                return ResourceManager.GetString("TestAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result.
        /// </summary>
        public static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thursday.
        /// </summary>
        public static string thu {
            get {
                return ResourceManager.GetString("thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee.
        /// </summary>
        public static string Trainee {
            get {
                return ResourceManager.GetString("Trainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee Archive.
        /// </summary>
        public static string TraineeArchive {
            get {
                return ResourceManager.GetString("TraineeArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee Attendance.
        /// </summary>
        public static string TraineeAttendance {
            get {
                return ResourceManager.GetString("TraineeAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee Attendance Absence Report.
        /// </summary>
        public static string TraineeAttendance_Absence {
            get {
                return ResourceManager.GetString("TraineeAttendance_Absence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Day.
        /// </summary>
        public static string TraineeAttendanceDay {
            get {
                return ResourceManager.GetString("TraineeAttendanceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraineeAttending Followup.
        /// </summary>
        public static string TraineeAttendingFollowup {
            get {
                return ResourceManager.GetString("TraineeAttendingFollowup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraineeEvaluation.
        /// </summary>
        public static string TraineeEvaluation {
            get {
                return ResourceManager.GetString("TraineeEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee File.
        /// </summary>
        public static string TraineeFile {
            get {
                return ResourceManager.GetString("TraineeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee TestResult.
        /// </summary>
        public static string TraineeTestResult {
            get {
                return ResourceManager.GetString("TraineeTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string tue {
            get {
                return ResourceManager.GetString("tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacations Deduction has been saved.
        /// </summary>
        public static string VacationDeductionSaved {
            get {
                return ResourceManager.GetString("VacationDeductionSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacations Deduction has been deleted.
        /// </summary>
        public static string VacationsDeductionDeleted {
            get {
                return ResourceManager.GetString("VacationsDeductionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacations Deduction has been edited.
        /// </summary>
        public static string VacationsDeductionEdited {
            get {
                return ResourceManager.GetString("VacationsDeductionEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter Value..
        /// </summary>
        public static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation has been deleted.
        /// </summary>
        public static string ViolationDeleted {
            get {
                return ResourceManager.GetString("ViolationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation has been edited.
        /// </summary>
        public static string ViolationEdited {
            get {
                return ResourceManager.GetString("ViolationEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation has been saved.
        /// </summary>
        public static string ViolationSaved {
            get {
                return ResourceManager.GetString("ViolationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation Setting has been edited.
        /// </summary>
        public static string ViolationTypeEdited {
            get {
                return ResourceManager.GetString("ViolationTypeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation Setting has been Saved.
        /// </summary>
        public static string ViolationTypeSaved {
            get {
                return ResourceManager.GetString("ViolationTypeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        public static string Visual {
            get {
                return ResourceManager.GetString("Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        public static string Visualdays {
            get {
                return ResourceManager.GetString("Visualdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wednesday.
        /// </summary>
        public static string wed {
            get {
                return ResourceManager.GetString("wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter With Salary/Form.
        /// </summary>
        public static string WithSalaryOrFormRequired {
            get {
                return ResourceManager.GetString("WithSalaryOrFormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hour Name has been deleted.
        /// </summary>
        public static string WorkingHourNameDeleted {
            get {
                return ResourceManager.GetString("WorkingHourNameDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours Detials have been deleted.
        /// </summary>
        public static string WorkingHoursDetialsDeleted {
            get {
                return ResourceManager.GetString("WorkingHoursDetialsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours Detials are existed already.Please enter another detials..
        /// </summary>
        public static string WorkingHoursDetialsExisted {
            get {
                return ResourceManager.GetString("WorkingHoursDetialsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours Detials have been added.
        /// </summary>
        public static string WorkingHoursSettingDetialsHRAdded {
            get {
                return ResourceManager.GetString("WorkingHoursSettingDetialsHRAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours Detials have been edited.
        /// </summary>
        public static string WorkingHoursSettingDetialsHREdited {
            get {
                return ResourceManager.GetString("WorkingHoursSettingDetialsHREdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hour Name has been edited.
        /// </summary>
        public static string WorkingHoursSettingHREdited {
            get {
                return ResourceManager.GetString("WorkingHoursSettingHREdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkTimes Setting.
        /// </summary>
        public static string WorkTimesSetting {
            get {
                return ResourceManager.GetString("WorkTimesSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Year--.
        /// </summary>
        public static string YearsDropDown {
            get {
                return ResourceManager.GetString("YearsDropDown", resourceCulture);
            }
        }
    }
}
