// <auto-generated />
namespace AutoDrive.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class WorkingHoursSettingDetialsHR_WorkingHoursSettingHRTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkingHoursSettingDetialsHR_WorkingHoursSettingHRTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202004282029128_WorkingHoursSettingDetialsHR_WorkingHoursSettingHRTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
